language: java
jdk:
- openjdk8

os:
- linux

deploy:
  provider: heroku
  api_key:
    secure: aa0ccff1-b80f-40a8-95e9-d74b14ae781b
  app: bookingapp-2
  on:
    repo: quangLinh9038/booking-app
    branch: feature-back
  skip_cleanup: 'true'
