language: java
jdk:
  - openjdk10

os:
  - linux
  - osx

dist:
  - precise
  - trusty

deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: booking-app1
  on:
    repo: quangLinh9038/booking-app
