language: java
jdk:
  - openjdk10

os:
  - linux
  - osx

dist:
  - precise
  - trusty

deploy:
  provider: heroku
  api_key: "TFLhMdXK7LQE5W1vBqjHKA"
  app: bookingapp-2
  on:
    repo: quangLinh9038/booking-app



