language: java
jdk:
  - openjdk10

os:
  - linux
  - osx

dist:
  - precise
  - trusty

deploy:
  provider: heroku
  api_key: "aa0ccff1-b80f-40a8-95e9-d74b14ae781b"
  app: bookingapp-2
  on:
    repo: quangLinh9038/booking-app



