language: java
jdk:
  - openjdk10

os:
  - linux
  - osx

dist:
  - precise
  - trusty

# deploy:
#   provider: heroku
#   api_key:
#     secure: "580caf8c-90ce-462c-8a11-f60b0d341924"
#   app: booking-app1
#   on:
#     repo: quangLinh9038/booking-app
